[2022-12-28 17:49:06,950] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 17:49:06,959] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 17:49:06,959] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:06,959] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 17:49:06,959] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:07,003] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2022-12-28 17:49:07,010] {standard_task_runner.py:52} INFO - Started process 14177 to run task
[2022-12-28 17:49:07,029] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpcocb03wh', '--error-file', '/tmp/tmps6rk4ww_']
[2022-12-28 17:49:07,035] {standard_task_runner.py:80} INFO - Job 13: Subtask cria_pasta
[2022-12-28 17:49:07,213] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 17:49:07,307] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 17:49:07,315] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20221228T204906, end_date=20221228T204907
[2022-12-28 17:49:07,376] {standard_task_runner.py:92} ERROR - Failed to execute job 13 for task cria_pasta (unexpected end of template, expected ','.; 14177)
[2022-12-28 17:49:07,410] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 17:49:07,540] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:13:53,941] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:13:54,012] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:13:54,013] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:13:54,013] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:13:54,013] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:13:54,073] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2022-12-28 18:13:54,079] {standard_task_runner.py:52} INFO - Started process 16807 to run task
[2022-12-28 18:13:54,099] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp1xam5ghg', '--error-file', '/tmp/tmpfmqd6gbv']
[2022-12-28 18:13:54,106] {standard_task_runner.py:80} INFO - Job 13: Subtask cria_pasta
[2022-12-28 18:13:54,346] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:13:54,534] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 18:13:54,551] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20221228T211353, end_date=20221228T211354
[2022-12-28 18:13:54,599] {standard_task_runner.py:92} ERROR - Failed to execute job 13 for task cria_pasta (unexpected end of template, expected ','.; 16807)
[2022-12-28 18:13:54,643] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 18:13:54,758] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:28:07,756] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:28:07,801] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:28:07,801] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:28:07,809] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:28:07,810] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:28:07,874] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2022-12-28 18:28:07,883] {standard_task_runner.py:52} INFO - Started process 18386 to run task
[2022-12-28 18:28:07,889] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpomc15rfw', '--error-file', '/tmp/tmppmhftj2g']
[2022-12-28 18:28:07,901] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2022-12-28 18:28:08,215] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:28:08,416] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2022-12-28 18:28:08,420] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:28:08,421] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-12"']
[2022-12-28 18:28:08,441] {subprocess.py:85} INFO - Output:
[2022-12-28 18:28:08,442] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:28:08,507] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20221228T212807, end_date=20221228T212808
[2022-12-28 18:28:08,613] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:28:08,686] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:37:41,729] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:37:41,760] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:37:41,761] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:37:41,761] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:37:41,761] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:37:41,834] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2022-12-28 18:37:41,842] {standard_task_runner.py:52} INFO - Started process 19424 to run task
[2022-12-28 18:37:41,881] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpjm4j_uj8', '--error-file', '/tmp/tmphzau1487']
[2022-12-28 18:37:41,883] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2022-12-28 18:37:42,248] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:37:42,528] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2022-12-28 18:37:42,530] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:37:42,537] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-12"']
[2022-12-28 18:37:42,549] {subprocess.py:85} INFO - Output:
[2022-12-28 18:37:42,557] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:37:42,675] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20221228T213741, end_date=20221228T213742
[2022-12-28 18:37:42,757] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:37:42,878] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:42:00,427] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:42:00,447] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:42:00,447] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:42:00,448] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:42:00,448] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:42:00,489] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2022-12-28 18:42:00,501] {standard_task_runner.py:52} INFO - Started process 19871 to run task
[2022-12-28 18:42:00,555] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpnx49tpe6', '--error-file', '/tmp/tmpe6qli1yh']
[2022-12-28 18:42:00,557] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2022-12-28 18:42:01,075] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:42:01,358] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2022-12-28 18:42:01,360] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:42:01,377] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-12"']
[2022-12-28 18:42:01,394] {subprocess.py:85} INFO - Output:
[2022-12-28 18:42:01,406] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:42:01,491] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20221228T214200, end_date=20221228T214201
[2022-12-28 18:42:01,594] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:42:01,728] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:44:09,263] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:44:09,323] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:44:09,323] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:44:09,332] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:44:09,334] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:44:09,419] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2022-12-28 18:44:09,440] {standard_task_runner.py:52} INFO - Started process 20131 to run task
[2022-12-28 18:44:09,475] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp1jyt8oie', '--error-file', '/tmp/tmp7o5pe8u0']
[2022-12-28 18:44:09,482] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2022-12-28 18:44:09,773] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:44:10,120] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2022-12-28 18:44:10,123] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:44:10,125] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-12"']
[2022-12-28 18:44:10,156] {subprocess.py:85} INFO - Output:
[2022-12-28 18:44:10,157] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:44:10,291] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20221228T214409, end_date=20221228T214410
[2022-12-28 18:44:10,385] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:44:10,488] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:51:39,100] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:51:39,112] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-12-28 18:51:39,112] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:51:39,113] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:51:39,113] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:51:39,177] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2022-12-28 18:51:39,189] {standard_task_runner.py:52} INFO - Started process 20948 to run task
[2022-12-28 18:51:39,197] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmprd3ncfcf', '--error-file', '/tmp/tmpt5s_0uif']
[2022-12-28 18:51:39,203] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2022-12-28 18:51:39,353] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:51:39,721] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2022-12-28 18:51:39,733] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:51:39,735] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-12"']
[2022-12-28 18:51:39,770] {subprocess.py:85} INFO - Output:
[2022-12-28 18:51:39,815] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:51:39,994] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20221228T215139, end_date=20221228T215139
[2022-12-28 18:51:40,072] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:51:40,171] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
