[2022-12-28 17:50:09,068] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-12-28 17:50:09,103] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-12-28 17:50:09,103] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:50:09,104] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 17:50:09,104] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:50:09,166] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2022-12-28 17:50:09,194] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp5v2ieh38', '--error-file', '/tmp/tmpxsw1y5qj']
[2022-12-28 17:50:09,196] {standard_task_runner.py:80} INFO - Job 23: Subtask cria_pasta
[2022-12-28 17:50:09,186] {standard_task_runner.py:52} INFO - Started process 14281 to run task
[2022-12-28 17:50:09,333] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 17:50:09,445] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 17:50:09,468] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20221228T205009, end_date=20221228T205009
[2022-12-28 17:50:09,513] {standard_task_runner.py:92} ERROR - Failed to execute job 23 for task cria_pasta (unexpected end of template, expected ','.; 14281)
[2022-12-28 17:50:09,548] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 17:50:09,690] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:14:43,758] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-12-28 18:14:43,768] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-12-28 18:14:43,768] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:43,768] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:14:43,768] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:43,807] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2022-12-28 18:14:43,815] {standard_task_runner.py:52} INFO - Started process 16917 to run task
[2022-12-28 18:14:43,820] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpr05do4c7', '--error-file', '/tmp/tmpa45e0sci']
[2022-12-28 18:14:43,821] {standard_task_runner.py:80} INFO - Job 23: Subtask cria_pasta
[2022-12-28 18:14:43,885] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:14:43,993] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 18:14:44,006] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20221228T211443, end_date=20221228T211444
[2022-12-28 18:14:44,033] {standard_task_runner.py:92} ERROR - Failed to execute job 23 for task cria_pasta (unexpected end of template, expected ','.; 16917)
[2022-12-28 18:14:44,045] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 18:14:44,205] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:29:48,201] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-12-28 18:29:48,211] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-12-28 18:29:48,211] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:29:48,211] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:29:48,211] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:29:48,253] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2022-12-28 18:29:48,259] {standard_task_runner.py:52} INFO - Started process 18568 to run task
[2022-12-28 18:29:48,296] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpzs9jq3f2', '--error-file', '/tmp/tmp7ef7ggtp']
[2022-12-28 18:29:48,297] {standard_task_runner.py:80} INFO - Job 34: Subtask cria_pasta
[2022-12-28 18:29:48,456] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:29:48,583] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2022-12-28 18:29:48,590] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:29:48,591] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-11-21"']
[2022-12-28 18:29:48,613] {subprocess.py:85} INFO - Output:
[2022-12-28 18:29:48,623] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:29:48,673] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20221228T212948, end_date=20221228T212948
[2022-12-28 18:29:48,721] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:29:48,823] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:46:26,420] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-12-28 18:46:26,432] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-12-28 18:46:26,432] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:46:26,432] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:46:26,432] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:46:26,494] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2022-12-28 18:46:26,511] {standard_task_runner.py:52} INFO - Started process 20350 to run task
[2022-12-28 18:46:26,528] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpehokammh', '--error-file', '/tmp/tmppx7o0912']
[2022-12-28 18:46:26,530] {standard_task_runner.py:80} INFO - Job 35: Subtask cria_pasta
[2022-12-28 18:46:26,657] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:46:26,770] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2022-12-28 18:46:26,772] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:46:26,773] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-11-21"']
[2022-12-28 18:46:26,794] {subprocess.py:85} INFO - Output:
[2022-12-28 18:46:26,833] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:46:26,986] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20221228T214626, end_date=20221228T214626
[2022-12-28 18:46:27,071] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:46:27,170] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:53:41,741] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-12-28 18:53:41,770] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-12-28 18:53:41,770] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:53:41,771] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:53:41,771] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:53:41,886] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2022-12-28 18:53:41,904] {standard_task_runner.py:52} INFO - Started process 21173 to run task
[2022-12-28 18:53:41,920] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp4j3w2buv', '--error-file', '/tmp/tmpxke16jwm']
[2022-12-28 18:53:41,926] {standard_task_runner.py:80} INFO - Job 35: Subtask cria_pasta
[2022-12-28 18:53:42,156] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:53:42,456] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2022-12-28 18:53:42,458] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:53:42,461] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-11-21"']
[2022-12-28 18:53:42,476] {subprocess.py:85} INFO - Output:
[2022-12-28 18:53:42,482] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:53:42,532] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20221228T215341, end_date=20221228T215342
[2022-12-28 18:53:42,599] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:53:42,707] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
