[2022-12-28 17:49:50,813] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2022-12-28 17:49:50,825] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2022-12-28 17:49:50,825] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:50,825] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 17:49:50,825] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:50,894] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-24 00:00:00+00:00
[2022-12-28 17:49:50,906] {standard_task_runner.py:52} INFO - Started process 14252 to run task
[2022-12-28 17:49:50,920] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp5hdvrw20', '--error-file', '/tmp/tmpmwnx49jk']
[2022-12-28 17:49:50,921] {standard_task_runner.py:80} INFO - Job 20: Subtask cria_pasta
[2022-12-28 17:49:51,114] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 17:49:51,172] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 17:49:51,183] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221024T000000, start_date=20221228T204950, end_date=20221228T204951
[2022-12-28 17:49:51,210] {standard_task_runner.py:92} ERROR - Failed to execute job 20 for task cria_pasta (unexpected end of template, expected ','.; 14252)
[2022-12-28 17:49:51,239] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 17:49:51,361] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:14:29,355] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2022-12-28 18:14:29,372] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2022-12-28 18:14:29,372] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:29,373] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:14:29,373] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:29,416] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-24 00:00:00+00:00
[2022-12-28 18:14:29,421] {standard_task_runner.py:52} INFO - Started process 16879 to run task
[2022-12-28 18:14:29,446] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpy1l3ms1x', '--error-file', '/tmp/tmp98vjv3bq']
[2022-12-28 18:14:29,448] {standard_task_runner.py:80} INFO - Job 20: Subtask cria_pasta
[2022-12-28 18:14:29,595] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:14:29,709] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 18:14:29,720] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221024T000000, start_date=20221228T211429, end_date=20221228T211429
[2022-12-28 18:14:29,748] {standard_task_runner.py:92} ERROR - Failed to execute job 20 for task cria_pasta (unexpected end of template, expected ','.; 16879)
[2022-12-28 18:14:29,757] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 18:14:29,881] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:29:23,169] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2022-12-28 18:29:23,182] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2022-12-28 18:29:23,182] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:29:23,183] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:29:23,183] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:29:23,219] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-24 00:00:00+00:00
[2022-12-28 18:29:23,235] {standard_task_runner.py:52} INFO - Started process 18520 to run task
[2022-12-28 18:29:23,269] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp8eboc7v4', '--error-file', '/tmp/tmpa7dk64ba']
[2022-12-28 18:29:23,270] {standard_task_runner.py:80} INFO - Job 28: Subtask cria_pasta
[2022-12-28 18:29:23,407] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:29:23,524] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-24T00:00:00+00:00
[2022-12-28 18:29:23,538] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:29:23,540] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-31"']
[2022-12-28 18:29:23,577] {subprocess.py:85} INFO - Output:
[2022-12-28 18:29:23,580] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:29:23,766] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221024T000000, start_date=20221228T212923, end_date=20221228T212923
[2022-12-28 18:29:23,853] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:29:24,126] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:45:48,496] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2022-12-28 18:45:48,511] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2022-12-28 18:45:48,512] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:45:48,512] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:45:48,512] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:45:48,542] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-24 00:00:00+00:00
[2022-12-28 18:45:48,547] {standard_task_runner.py:52} INFO - Started process 20286 to run task
[2022-12-28 18:45:48,565] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpr53u8dgz', '--error-file', '/tmp/tmpgl__as_g']
[2022-12-28 18:45:48,566] {standard_task_runner.py:80} INFO - Job 29: Subtask cria_pasta
[2022-12-28 18:45:48,770] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:45:48,988] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-24T00:00:00+00:00
[2022-12-28 18:45:48,991] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:45:48,993] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-31"']
[2022-12-28 18:45:49,021] {subprocess.py:85} INFO - Output:
[2022-12-28 18:45:49,023] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:45:49,116] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221024T000000, start_date=20221228T214548, end_date=20221228T214549
[2022-12-28 18:45:49,187] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:45:49,301] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:53:09,595] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2022-12-28 18:53:09,614] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2022-12-28 18:53:09,614] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:53:09,614] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:53:09,614] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:53:09,666] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-24 00:00:00+00:00
[2022-12-28 18:53:09,679] {standard_task_runner.py:52} INFO - Started process 21114 to run task
[2022-12-28 18:53:09,696] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpf3229bqk', '--error-file', '/tmp/tmpnmba4mjh']
[2022-12-28 18:53:09,697] {standard_task_runner.py:80} INFO - Job 29: Subtask cria_pasta
[2022-12-28 18:53:09,812] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:53:09,933] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-24T00:00:00+00:00
[2022-12-28 18:53:09,935] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:53:09,936] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-31"']
[2022-12-28 18:53:09,972] {subprocess.py:85} INFO - Output:
[2022-12-28 18:53:09,980] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:53:10,030] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221024T000000, start_date=20221228T215309, end_date=20221228T215310
[2022-12-28 18:53:10,098] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:53:10,162] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
