[2022-12-28 17:50:03,380] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-12-28 17:50:03,404] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-12-28 17:50:03,404] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:50:03,405] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 17:50:03,405] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:50:03,466] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-07 00:00:00+00:00
[2022-12-28 17:50:03,473] {standard_task_runner.py:52} INFO - Started process 14274 to run task
[2022-12-28 17:50:03,483] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-07T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpohfav4f9', '--error-file', '/tmp/tmp799ihdn3']
[2022-12-28 17:50:03,484] {standard_task_runner.py:80} INFO - Job 22: Subtask cria_pasta
[2022-12-28 17:50:03,665] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 17:50:03,762] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 17:50:03,791] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221107T000000, start_date=20221228T205003, end_date=20221228T205003
[2022-12-28 17:50:03,868] {standard_task_runner.py:92} ERROR - Failed to execute job 22 for task cria_pasta (unexpected end of template, expected ','.; 14274)
[2022-12-28 17:50:03,908] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 17:50:04,007] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:14:38,914] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-12-28 18:14:38,923] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-12-28 18:14:38,923] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:38,923] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:14:38,923] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:38,965] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-07 00:00:00+00:00
[2022-12-28 18:14:38,972] {standard_task_runner.py:52} INFO - Started process 16903 to run task
[2022-12-28 18:14:38,979] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-07T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpnxrnf5w9', '--error-file', '/tmp/tmpe77a1hs7']
[2022-12-28 18:14:38,980] {standard_task_runner.py:80} INFO - Job 22: Subtask cria_pasta
[2022-12-28 18:14:39,046] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:14:39,099] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 18:14:39,108] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221107T000000, start_date=20221228T211438, end_date=20221228T211439
[2022-12-28 18:14:39,135] {standard_task_runner.py:92} ERROR - Failed to execute job 22 for task cria_pasta (unexpected end of template, expected ','.; 16903)
[2022-12-28 18:14:39,155] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 18:14:39,219] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:29:40,414] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-12-28 18:29:40,422] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-12-28 18:29:40,422] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:29:40,422] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:29:40,423] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:29:40,453] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-07 00:00:00+00:00
[2022-12-28 18:29:40,458] {standard_task_runner.py:52} INFO - Started process 18552 to run task
[2022-12-28 18:29:40,466] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-07T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmptl7nfp4w', '--error-file', '/tmp/tmp0m62wcw3']
[2022-12-28 18:29:40,478] {standard_task_runner.py:80} INFO - Job 32: Subtask cria_pasta
[2022-12-28 18:29:40,570] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:29:40,683] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-07T00:00:00+00:00
[2022-12-28 18:29:40,687] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:29:40,688] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-11-14"']
[2022-12-28 18:29:40,728] {subprocess.py:85} INFO - Output:
[2022-12-28 18:29:40,742] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:29:40,796] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221107T000000, start_date=20221228T212940, end_date=20221228T212940
[2022-12-28 18:29:40,864] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:29:40,964] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:46:06,484] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-12-28 18:46:06,507] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-12-28 18:46:06,507] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:46:06,520] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:46:06,520] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:46:06,588] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-07 00:00:00+00:00
[2022-12-28 18:46:06,598] {standard_task_runner.py:52} INFO - Started process 20321 to run task
[2022-12-28 18:46:06,623] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-07T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpxt2d19y8', '--error-file', '/tmp/tmpi8gqem2m']
[2022-12-28 18:46:06,625] {standard_task_runner.py:80} INFO - Job 32: Subtask cria_pasta
[2022-12-28 18:46:06,787] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:46:06,995] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-07T00:00:00+00:00
[2022-12-28 18:46:06,997] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:46:06,997] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-11-14"']
[2022-12-28 18:46:07,052] {subprocess.py:85} INFO - Output:
[2022-12-28 18:46:07,071] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:46:07,150] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221107T000000, start_date=20221228T214606, end_date=20221228T214607
[2022-12-28 18:46:07,259] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:46:07,392] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:53:22,527] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-12-28 18:53:22,548] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-12-28 18:53:22,549] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:53:22,549] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:53:22,549] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:53:22,580] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-07 00:00:00+00:00
[2022-12-28 18:53:22,590] {standard_task_runner.py:52} INFO - Started process 21138 to run task
[2022-12-28 18:53:22,596] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-07T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpbcmxnbxb', '--error-file', '/tmp/tmp8uaju63h']
[2022-12-28 18:53:22,602] {standard_task_runner.py:80} INFO - Job 32: Subtask cria_pasta
[2022-12-28 18:53:22,734] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:53:22,945] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-07T00:00:00+00:00
[2022-12-28 18:53:22,949] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:53:22,953] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-11-14"']
[2022-12-28 18:53:22,967] {subprocess.py:85} INFO - Output:
[2022-12-28 18:53:22,976] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:53:23,037] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221107T000000, start_date=20221228T215322, end_date=20221228T215323
[2022-12-28 18:53:23,101] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:53:23,183] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
