[2022-12-28 17:50:15,749] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-12-28 17:50:15,762] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-12-28 17:50:15,773] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:50:15,773] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 17:50:15,773] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:50:15,818] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-21 00:00:00+00:00
[2022-12-28 17:50:15,833] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpnvkp17m3', '--error-file', '/tmp/tmpwts546ge']
[2022-12-28 17:50:15,835] {standard_task_runner.py:80} INFO - Job 24: Subtask cria_pasta
[2022-12-28 17:50:15,825] {standard_task_runner.py:52} INFO - Started process 14294 to run task
[2022-12-28 17:50:16,001] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 17:50:16,094] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 17:50:16,104] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221121T000000, start_date=20221228T205015, end_date=20221228T205016
[2022-12-28 17:50:16,141] {standard_task_runner.py:92} ERROR - Failed to execute job 24 for task cria_pasta (unexpected end of template, expected ','.; 14294)
[2022-12-28 17:50:16,157] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 17:50:16,275] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:14:48,367] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-12-28 18:14:48,380] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-12-28 18:14:48,380] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:48,380] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:14:48,380] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:48,440] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-21 00:00:00+00:00
[2022-12-28 18:14:48,456] {standard_task_runner.py:52} INFO - Started process 16924 to run task
[2022-12-28 18:14:48,474] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp3wikozcd', '--error-file', '/tmp/tmp6ewonurg']
[2022-12-28 18:14:48,476] {standard_task_runner.py:80} INFO - Job 24: Subtask cria_pasta
[2022-12-28 18:14:48,684] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:14:48,810] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 18:14:48,820] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221121T000000, start_date=20221228T211448, end_date=20221228T211448
[2022-12-28 18:14:48,872] {standard_task_runner.py:92} ERROR - Failed to execute job 24 for task cria_pasta (unexpected end of template, expected ','.; 16924)
[2022-12-28 18:14:48,956] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 18:14:49,060] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:30:01,232] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-12-28 18:30:01,244] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-12-28 18:30:01,244] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:30:01,244] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:30:01,245] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:30:01,290] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-21 00:00:00+00:00
[2022-12-28 18:30:01,297] {standard_task_runner.py:52} INFO - Started process 18591 to run task
[2022-12-28 18:30:01,314] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpa7boeowp', '--error-file', '/tmp/tmpzzlzf9ne']
[2022-12-28 18:30:01,315] {standard_task_runner.py:80} INFO - Job 37: Subtask cria_pasta
[2022-12-28 18:30:01,490] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:30:01,648] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-12-28 18:30:01,653] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:30:01,654] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-11-28"']
[2022-12-28 18:30:01,671] {subprocess.py:85} INFO - Output:
[2022-12-28 18:30:01,674] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:30:01,772] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221121T000000, start_date=20221228T213001, end_date=20221228T213001
[2022-12-28 18:30:01,895] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:30:01,993] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:46:31,982] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-12-28 18:46:31,996] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-12-28 18:46:31,996] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:46:31,996] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:46:31,996] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:46:32,055] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-21 00:00:00+00:00
[2022-12-28 18:46:32,078] {standard_task_runner.py:52} INFO - Started process 20361 to run task
[2022-12-28 18:46:32,083] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpkz_a9jc2', '--error-file', '/tmp/tmpfegt4j8k']
[2022-12-28 18:46:32,085] {standard_task_runner.py:80} INFO - Job 36: Subtask cria_pasta
[2022-12-28 18:46:32,308] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:46:32,483] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-12-28 18:46:32,485] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:46:32,488] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-11-28"']
[2022-12-28 18:46:32,515] {subprocess.py:85} INFO - Output:
[2022-12-28 18:46:32,516] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:46:32,611] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221121T000000, start_date=20221228T214631, end_date=20221228T214632
[2022-12-28 18:46:32,697] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:46:32,803] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:53:49,126] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-12-28 18:53:49,154] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-12-28 18:53:49,155] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:53:49,155] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:53:49,155] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:53:49,241] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-21 00:00:00+00:00
[2022-12-28 18:53:49,248] {standard_task_runner.py:52} INFO - Started process 21188 to run task
[2022-12-28 18:53:49,266] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpt2ujue44', '--error-file', '/tmp/tmpjqq3bbjc']
[2022-12-28 18:53:49,268] {standard_task_runner.py:80} INFO - Job 36: Subtask cria_pasta
[2022-12-28 18:53:49,510] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:53:49,750] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-12-28 18:53:49,752] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:53:49,753] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-11-28"']
[2022-12-28 18:53:49,771] {subprocess.py:85} INFO - Output:
[2022-12-28 18:53:49,777] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:53:49,866] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221121T000000, start_date=20221228T215349, end_date=20221228T215349
[2022-12-28 18:53:50,089] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:53:50,507] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
