[2022-12-28 17:49:26,126] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 17:49:26,136] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 17:49:26,136] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:26,136] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 17:49:26,136] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:26,197] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2022-12-28 17:49:26,203] {standard_task_runner.py:52} INFO - Started process 14209 to run task
[2022-12-28 17:49:26,212] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpt_y569nq', '--error-file', '/tmp/tmpqmh9taim']
[2022-12-28 17:49:26,236] {standard_task_runner.py:80} INFO - Job 16: Subtask cria_pasta
[2022-12-28 17:49:26,527] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 17:49:26,633] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 17:49:26,647] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20221228T204926, end_date=20221228T204926
[2022-12-28 17:49:26,693] {standard_task_runner.py:92} ERROR - Failed to execute job 16 for task cria_pasta (unexpected end of template, expected ','.; 14209)
[2022-12-28 17:49:26,752] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 17:49:26,887] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:14:11,906] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:14:11,917] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:14:11,917] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:11,918] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:14:11,918] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:11,951] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2022-12-28 18:14:11,963] {standard_task_runner.py:52} INFO - Started process 16843 to run task
[2022-12-28 18:14:11,975] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmprsax2cax', '--error-file', '/tmp/tmpuvnbf6pc']
[2022-12-28 18:14:11,976] {standard_task_runner.py:80} INFO - Job 16: Subtask cria_pasta
[2022-12-28 18:14:12,052] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:14:12,165] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 18:14:12,177] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20221228T211411, end_date=20221228T211412
[2022-12-28 18:14:12,273] {standard_task_runner.py:92} ERROR - Failed to execute job 16 for task cria_pasta (unexpected end of template, expected ','.; 16843)
[2022-12-28 18:14:12,318] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 18:14:12,372] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:28:44,850] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:28:44,863] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:28:44,863] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:28:44,863] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:28:44,863] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:28:44,914] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2022-12-28 18:28:44,929] {standard_task_runner.py:52} INFO - Started process 18447 to run task
[2022-12-28 18:28:44,940] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpyhmwnu4h', '--error-file', '/tmp/tmpmf5378r0']
[2022-12-28 18:28:44,953] {standard_task_runner.py:80} INFO - Job 20: Subtask cria_pasta
[2022-12-28 18:28:45,121] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:28:45,263] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2022-12-28 18:28:45,277] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:28:45,278] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-03"']
[2022-12-28 18:28:45,336] {subprocess.py:85} INFO - Output:
[2022-12-28 18:28:45,364] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:28:45,480] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20221228T212844, end_date=20221228T212845
[2022-12-28 18:28:45,555] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:28:45,632] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:38:18,300] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:38:18,344] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:38:18,345] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:38:18,345] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:38:18,345] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:38:18,421] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2022-12-28 18:38:18,426] {standard_task_runner.py:52} INFO - Started process 19478 to run task
[2022-12-28 18:38:18,438] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpaou9w1hz', '--error-file', '/tmp/tmpisgu92uh']
[2022-12-28 18:38:18,441] {standard_task_runner.py:80} INFO - Job 20: Subtask cria_pasta
[2022-12-28 18:38:18,681] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:38:18,938] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2022-12-28 18:38:18,940] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:38:18,945] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-03"']
[2022-12-28 18:38:18,961] {subprocess.py:85} INFO - Output:
[2022-12-28 18:38:18,967] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:38:19,091] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20221228T213818, end_date=20221228T213819
[2022-12-28 18:38:19,273] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:38:19,372] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:42:36,833] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:42:36,845] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:42:36,846] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:42:36,846] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:42:36,846] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:42:36,893] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2022-12-28 18:42:36,901] {standard_task_runner.py:52} INFO - Started process 19925 to run task
[2022-12-28 18:42:36,907] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpo8wcyrwa', '--error-file', '/tmp/tmpfv3fioza']
[2022-12-28 18:42:36,909] {standard_task_runner.py:80} INFO - Job 20: Subtask cria_pasta
[2022-12-28 18:42:37,067] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:42:37,196] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2022-12-28 18:42:37,198] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:42:37,199] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-03"']
[2022-12-28 18:42:37,230] {subprocess.py:85} INFO - Output:
[2022-12-28 18:42:37,240] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:42:37,292] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20221228T214236, end_date=20221228T214237
[2022-12-28 18:42:37,351] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:42:37,443] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:44:52,844] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:44:52,862] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:44:52,862] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:44:52,862] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:44:52,862] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:44:52,897] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2022-12-28 18:44:52,903] {standard_task_runner.py:52} INFO - Started process 20204 to run task
[2022-12-28 18:44:52,931] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpa7orbv6w', '--error-file', '/tmp/tmpzafjdpsu']
[2022-12-28 18:44:52,933] {standard_task_runner.py:80} INFO - Job 20: Subtask cria_pasta
[2022-12-28 18:44:53,090] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:44:53,277] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2022-12-28 18:44:53,278] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:44:53,279] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-03"']
[2022-12-28 18:44:53,321] {subprocess.py:85} INFO - Output:
[2022-12-28 18:44:53,330] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:44:53,401] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20221228T214452, end_date=20221228T214453
[2022-12-28 18:44:53,464] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:44:53,563] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:52:22,437] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:52:22,455] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-12-28 18:52:22,455] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:52:22,456] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:52:22,456] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:52:22,487] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2022-12-28 18:52:22,493] {standard_task_runner.py:52} INFO - Started process 21021 to run task
[2022-12-28 18:52:22,499] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpodaefgq4', '--error-file', '/tmp/tmp_euroy0o']
[2022-12-28 18:52:22,500] {standard_task_runner.py:80} INFO - Job 20: Subtask cria_pasta
[2022-12-28 18:52:22,606] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:52:22,732] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2022-12-28 18:52:22,737] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:52:22,738] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-03"']
[2022-12-28 18:52:22,804] {subprocess.py:85} INFO - Output:
[2022-12-28 18:52:22,815] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:52:22,914] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20221228T215222, end_date=20221228T215222
[2022-12-28 18:52:23,018] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:52:23,161] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
