[2022-12-28 17:49:38,783] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 17:49:38,802] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 17:49:38,803] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:38,806] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 17:49:38,808] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:38,849] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-10 00:00:00+00:00
[2022-12-28 17:49:38,855] {standard_task_runner.py:52} INFO - Started process 14232 to run task
[2022-12-28 17:49:38,865] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp8nlthjzv', '--error-file', '/tmp/tmpmvxf8wdy']
[2022-12-28 17:49:38,866] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2022-12-28 17:49:38,981] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 17:49:39,032] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 17:49:39,043] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221010T000000, start_date=20221228T204938, end_date=20221228T204939
[2022-12-28 17:49:39,072] {standard_task_runner.py:92} ERROR - Failed to execute job 18 for task cria_pasta (unexpected end of template, expected ','.; 14232)
[2022-12-28 17:49:39,122] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 17:49:39,236] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:14:20,711] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 18:14:20,773] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 18:14:20,774] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:20,781] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:14:20,781] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:20,828] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-10 00:00:00+00:00
[2022-12-28 18:14:20,834] {standard_task_runner.py:52} INFO - Started process 16864 to run task
[2022-12-28 18:14:20,891] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp01dkzqfc', '--error-file', '/tmp/tmp6d7qgp96']
[2022-12-28 18:14:20,892] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2022-12-28 18:14:21,181] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:14:21,304] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 18:14:21,334] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221010T000000, start_date=20221228T211420, end_date=20221228T211421
[2022-12-28 18:14:21,379] {standard_task_runner.py:92} ERROR - Failed to execute job 18 for task cria_pasta (unexpected end of template, expected ','.; 16864)
[2022-12-28 18:14:21,407] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 18:14:21,516] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:29:10,282] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 18:29:10,296] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 18:29:10,296] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:29:10,296] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:29:10,296] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:29:10,347] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-10 00:00:00+00:00
[2022-12-28 18:29:10,358] {standard_task_runner.py:52} INFO - Started process 18493 to run task
[2022-12-28 18:29:10,380] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmphb57m0al', '--error-file', '/tmp/tmpkf0lzghq']
[2022-12-28 18:29:10,381] {standard_task_runner.py:80} INFO - Job 25: Subtask cria_pasta
[2022-12-28 18:29:10,501] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:29:10,678] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-10T00:00:00+00:00
[2022-12-28 18:29:10,681] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:29:10,682] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-17"']
[2022-12-28 18:29:10,702] {subprocess.py:85} INFO - Output:
[2022-12-28 18:29:10,709] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:29:10,777] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221010T000000, start_date=20221228T212910, end_date=20221228T212910
[2022-12-28 18:29:10,843] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:29:10,966] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:38:48,638] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 18:38:48,675] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 18:38:48,675] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:38:48,675] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:38:48,675] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:38:48,726] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-10 00:00:00+00:00
[2022-12-28 18:38:48,741] {standard_task_runner.py:52} INFO - Started process 19532 to run task
[2022-12-28 18:38:48,759] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpr44th2j_', '--error-file', '/tmp/tmpmzto72bs']
[2022-12-28 18:38:48,761] {standard_task_runner.py:80} INFO - Job 25: Subtask cria_pasta
[2022-12-28 18:38:48,944] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:38:49,239] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-10T00:00:00+00:00
[2022-12-28 18:38:49,303] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:38:49,304] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-17"']
[2022-12-28 18:38:49,372] {subprocess.py:85} INFO - Output:
[2022-12-28 18:38:49,380] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:38:49,600] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221010T000000, start_date=20221228T213848, end_date=20221228T213849
[2022-12-28 18:38:49,684] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:38:49,850] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:45:17,248] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 18:45:17,269] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 18:45:17,269] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:45:17,270] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:45:17,270] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:45:17,326] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-10 00:00:00+00:00
[2022-12-28 18:45:17,335] {standard_task_runner.py:52} INFO - Started process 20239 to run task
[2022-12-28 18:45:17,350] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmps4pqutre', '--error-file', '/tmp/tmp6rrum9rn']
[2022-12-28 18:45:17,352] {standard_task_runner.py:80} INFO - Job 24: Subtask cria_pasta
[2022-12-28 18:45:17,522] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:45:17,701] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-10T00:00:00+00:00
[2022-12-28 18:45:17,703] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:45:17,704] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-17"']
[2022-12-28 18:45:17,722] {subprocess.py:85} INFO - Output:
[2022-12-28 18:45:17,732] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:45:17,849] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221010T000000, start_date=20221228T214517, end_date=20221228T214517
[2022-12-28 18:45:17,951] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:45:18,126] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:52:42,976] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 18:52:42,992] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-12-28 18:52:42,993] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:52:42,993] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:52:42,993] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:52:43,024] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-10 00:00:00+00:00
[2022-12-28 18:52:43,030] {standard_task_runner.py:52} INFO - Started process 21065 to run task
[2022-12-28 18:52:43,048] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpuhhx87i9', '--error-file', '/tmp/tmpvryn7ell']
[2022-12-28 18:52:43,049] {standard_task_runner.py:80} INFO - Job 24: Subtask cria_pasta
[2022-12-28 18:52:43,148] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:52:43,279] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-10T00:00:00+00:00
[2022-12-28 18:52:43,281] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:52:43,282] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-17"']
[2022-12-28 18:52:43,331] {subprocess.py:85} INFO - Output:
[2022-12-28 18:52:43,334] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:52:43,390] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221010T000000, start_date=20221228T215242, end_date=20221228T215243
[2022-12-28 18:52:43,459] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:52:43,522] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
