[2022-12-28 17:49:31,822] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 17:49:31,846] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 17:49:31,856] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:31,857] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 17:49:31,857] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:31,912] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2022-12-28 17:49:31,920] {standard_task_runner.py:52} INFO - Started process 14218 to run task
[2022-12-28 17:49:31,946] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmphogron8x', '--error-file', '/tmp/tmp_t_bu8te']
[2022-12-28 17:49:31,948] {standard_task_runner.py:80} INFO - Job 17: Subtask cria_pasta
[2022-12-28 17:49:32,101] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 17:49:32,204] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 17:49:32,261] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20221228T204931, end_date=20221228T204932
[2022-12-28 17:49:32,292] {standard_task_runner.py:92} ERROR - Failed to execute job 17 for task cria_pasta (unexpected end of template, expected ','.; 14218)
[2022-12-28 17:49:32,311] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 17:49:32,423] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:14:16,609] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:14:16,619] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:14:16,619] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:16,619] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:14:16,619] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:16,677] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2022-12-28 18:14:16,683] {standard_task_runner.py:52} INFO - Started process 16858 to run task
[2022-12-28 18:14:16,691] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpgmb0q_os', '--error-file', '/tmp/tmpwtvgnwlc']
[2022-12-28 18:14:16,693] {standard_task_runner.py:80} INFO - Job 17: Subtask cria_pasta
[2022-12-28 18:14:16,780] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:14:16,861] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 18:14:16,870] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20221228T211416, end_date=20221228T211416
[2022-12-28 18:14:16,908] {standard_task_runner.py:92} ERROR - Failed to execute job 17 for task cria_pasta (unexpected end of template, expected ','.; 16858)
[2022-12-28 18:14:16,924] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 18:14:16,977] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:28:55,639] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:28:55,652] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:28:55,652] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:28:55,653] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:28:55,653] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:28:55,688] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2022-12-28 18:28:55,698] {standard_task_runner.py:52} INFO - Started process 18468 to run task
[2022-12-28 18:28:55,717] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpdx2qr4g3', '--error-file', '/tmp/tmpfuyzbqxx']
[2022-12-28 18:28:55,722] {standard_task_runner.py:80} INFO - Job 22: Subtask cria_pasta
[2022-12-28 18:28:55,824] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:28:55,990] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-03T00:00:00+00:00
[2022-12-28 18:28:55,992] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:28:55,993] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-10"']
[2022-12-28 18:28:56,009] {subprocess.py:85} INFO - Output:
[2022-12-28 18:28:56,021] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:28:56,081] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20221228T212855, end_date=20221228T212856
[2022-12-28 18:28:56,157] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:28:56,246] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:38:30,181] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:38:30,240] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:38:30,241] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:38:30,241] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:38:30,241] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:38:30,300] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2022-12-28 18:38:30,308] {standard_task_runner.py:52} INFO - Started process 19496 to run task
[2022-12-28 18:38:30,318] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp8wz_0ru5', '--error-file', '/tmp/tmpraxasua4']
[2022-12-28 18:38:30,335] {standard_task_runner.py:80} INFO - Job 22: Subtask cria_pasta
[2022-12-28 18:38:30,557] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:38:30,955] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-03T00:00:00+00:00
[2022-12-28 18:38:30,960] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:38:30,968] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-10"']
[2022-12-28 18:38:30,988] {subprocess.py:85} INFO - Output:
[2022-12-28 18:38:30,993] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:38:31,113] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20221228T213830, end_date=20221228T213831
[2022-12-28 18:38:31,244] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:38:31,355] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:42:56,470] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:42:56,485] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:42:56,486] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:42:56,486] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:42:56,486] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:42:56,530] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2022-12-28 18:42:56,542] {standard_task_runner.py:52} INFO - Started process 19960 to run task
[2022-12-28 18:42:56,555] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpf2mhi07l', '--error-file', '/tmp/tmpp9fyw88e']
[2022-12-28 18:42:56,556] {standard_task_runner.py:80} INFO - Job 23: Subtask cria_pasta
[2022-12-28 18:42:56,707] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:42:56,900] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-03T00:00:00+00:00
[2022-12-28 18:42:56,903] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:42:56,910] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-10"']
[2022-12-28 18:42:56,937] {subprocess.py:85} INFO - Output:
[2022-12-28 18:42:56,946] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:42:57,030] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20221228T214256, end_date=20221228T214257
[2022-12-28 18:42:57,140] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:42:57,251] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:45:11,560] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:45:11,588] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:45:11,589] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:45:11,589] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:45:11,589] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:45:11,650] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2022-12-28 18:45:11,658] {standard_task_runner.py:52} INFO - Started process 20232 to run task
[2022-12-28 18:45:11,685] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmprcf97l7c', '--error-file', '/tmp/tmp0s4832hw']
[2022-12-28 18:45:11,689] {standard_task_runner.py:80} INFO - Job 23: Subtask cria_pasta
[2022-12-28 18:45:11,860] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:45:12,023] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-03T00:00:00+00:00
[2022-12-28 18:45:12,034] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:45:12,037] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-10"']
[2022-12-28 18:45:12,066] {subprocess.py:85} INFO - Output:
[2022-12-28 18:45:12,072] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:45:12,158] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20221228T214511, end_date=20221228T214512
[2022-12-28 18:45:12,246] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:45:12,350] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:52:38,567] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:52:38,583] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-12-28 18:52:38,584] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:52:38,584] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:52:38,584] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:52:38,618] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2022-12-28 18:52:38,631] {standard_task_runner.py:52} INFO - Started process 21053 to run task
[2022-12-28 18:52:38,648] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpxkqgsxe3', '--error-file', '/tmp/tmpagrg707z']
[2022-12-28 18:52:38,650] {standard_task_runner.py:80} INFO - Job 23: Subtask cria_pasta
[2022-12-28 18:52:38,827] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:52:38,953] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-03T00:00:00+00:00
[2022-12-28 18:52:38,958] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:52:38,960] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-10-10"']
[2022-12-28 18:52:38,981] {subprocess.py:85} INFO - Output:
[2022-12-28 18:52:38,986] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:52:39,060] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20221228T215238, end_date=20221228T215239
[2022-12-28 18:52:39,128] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:52:39,196] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
