[2022-12-28 17:49:13,599] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 17:49:13,610] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 17:49:13,610] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:13,610] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 17:49:13,610] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:13,648] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2022-12-28 17:49:13,655] {standard_task_runner.py:52} INFO - Started process 14185 to run task
[2022-12-28 17:49:13,676] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpxzygc_o4', '--error-file', '/tmp/tmponig5zvj']
[2022-12-28 17:49:13,691] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2022-12-28 17:49:13,878] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 17:49:13,944] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 17:49:13,961] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20221228T204913, end_date=20221228T204913
[2022-12-28 17:49:13,999] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task cria_pasta (unexpected end of template, expected ','.; 14185)
[2022-12-28 17:49:14,038] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 17:49:14,189] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:14:00,133] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:14:00,156] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:14:00,156] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:00,156] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:14:00,156] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:00,201] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2022-12-28 18:14:00,207] {standard_task_runner.py:52} INFO - Started process 16820 to run task
[2022-12-28 18:14:00,218] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmptz815bsa', '--error-file', '/tmp/tmpq1zg2f8v']
[2022-12-28 18:14:00,219] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2022-12-28 18:14:00,457] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:14:00,568] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 18:14:00,592] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20221228T211400, end_date=20221228T211400
[2022-12-28 18:14:00,779] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task cria_pasta (unexpected end of template, expected ','.; 16820)
[2022-12-28 18:14:00,831] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 18:14:00,982] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:28:20,351] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:28:20,369] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:28:20,369] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:28:20,369] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:28:20,369] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:28:20,412] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2022-12-28 18:28:20,421] {standard_task_runner.py:52} INFO - Started process 18404 to run task
[2022-12-28 18:28:20,437] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpmte7nj8n', '--error-file', '/tmp/tmph420d9_c']
[2022-12-28 18:28:20,438] {standard_task_runner.py:80} INFO - Job 16: Subtask cria_pasta
[2022-12-28 18:28:20,563] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:28:20,720] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2022-12-28 18:28:20,722] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:28:20,722] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-19"']
[2022-12-28 18:28:20,753] {subprocess.py:85} INFO - Output:
[2022-12-28 18:28:20,754] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:28:20,823] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20221228T212820, end_date=20221228T212820
[2022-12-28 18:28:20,954] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:28:21,152] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:38:01,936] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:38:01,949] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:38:01,949] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:38:01,949] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:38:01,950] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:38:02,031] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2022-12-28 18:38:02,037] {standard_task_runner.py:52} INFO - Started process 19454 to run task
[2022-12-28 18:38:02,043] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpij0l9f5t', '--error-file', '/tmp/tmp1pvmdqbq']
[2022-12-28 18:38:02,044] {standard_task_runner.py:80} INFO - Job 17: Subtask cria_pasta
[2022-12-28 18:38:02,211] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:38:02,430] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2022-12-28 18:38:02,432] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:38:02,433] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-19"']
[2022-12-28 18:38:02,460] {subprocess.py:85} INFO - Output:
[2022-12-28 18:38:02,463] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:38:02,575] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20221228T213801, end_date=20221228T213802
[2022-12-28 18:38:02,675] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:38:02,827] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:42:20,035] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:42:20,051] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:42:20,051] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:42:20,051] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:42:20,051] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:42:20,090] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2022-12-28 18:42:20,107] {standard_task_runner.py:52} INFO - Started process 19902 to run task
[2022-12-28 18:42:20,135] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmps20x1u2p', '--error-file', '/tmp/tmp5vwia1mg']
[2022-12-28 18:42:20,136] {standard_task_runner.py:80} INFO - Job 17: Subtask cria_pasta
[2022-12-28 18:42:20,283] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:42:20,419] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2022-12-28 18:42:20,421] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:42:20,422] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-19"']
[2022-12-28 18:42:20,460] {subprocess.py:85} INFO - Output:
[2022-12-28 18:42:20,461] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:42:20,536] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20221228T214220, end_date=20221228T214220
[2022-12-28 18:42:20,684] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:42:20,856] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:44:35,918] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:44:35,937] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:44:35,937] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:44:35,937] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:44:35,937] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:44:36,011] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2022-12-28 18:44:36,020] {standard_task_runner.py:52} INFO - Started process 20173 to run task
[2022-12-28 18:44:36,027] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpxrrafp3f', '--error-file', '/tmp/tmpwgh7jqun']
[2022-12-28 18:44:36,029] {standard_task_runner.py:80} INFO - Job 17: Subtask cria_pasta
[2022-12-28 18:44:36,241] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:44:36,402] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2022-12-28 18:44:36,404] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:44:36,407] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-19"']
[2022-12-28 18:44:36,429] {subprocess.py:85} INFO - Output:
[2022-12-28 18:44:36,437] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:44:36,554] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20221228T214435, end_date=20221228T214436
[2022-12-28 18:44:36,614] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:44:36,723] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:52:06,512] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:52:06,524] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-12-28 18:52:06,525] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:52:06,525] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:52:06,526] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:52:06,583] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2022-12-28 18:52:06,592] {standard_task_runner.py:52} INFO - Started process 20993 to run task
[2022-12-28 18:52:06,619] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpv9_dgumd', '--error-file', '/tmp/tmpxuxm_bcl']
[2022-12-28 18:52:06,620] {standard_task_runner.py:80} INFO - Job 17: Subtask cria_pasta
[2022-12-28 18:52:06,849] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:52:07,037] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2022-12-28 18:52:07,038] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:52:07,044] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-19"']
[2022-12-28 18:52:07,069] {subprocess.py:85} INFO - Output:
[2022-12-28 18:52:07,078] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:52:07,143] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20221228T215206, end_date=20221228T215207
[2022-12-28 18:52:07,235] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:52:07,339] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
