[2022-12-28 17:49:19,116] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 17:49:19,128] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 17:49:19,128] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:19,128] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 17:49:19,128] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 17:49:19,205] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2022-12-28 17:49:19,212] {standard_task_runner.py:52} INFO - Started process 14196 to run task
[2022-12-28 17:49:19,235] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp9b7qy55y', '--error-file', '/tmp/tmpn19gn7ku']
[2022-12-28 17:49:19,236] {standard_task_runner.py:80} INFO - Job 15: Subtask cria_pasta
[2022-12-28 17:49:19,380] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 17:49:19,496] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 17:49:19,510] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20221228T204919, end_date=20221228T204919
[2022-12-28 17:49:19,560] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task cria_pasta (unexpected end of template, expected ','.; 14196)
[2022-12-28 17:49:19,632] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 17:49:19,784] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:14:07,722] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:14:07,733] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:14:07,733] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:07,733] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:14:07,733] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:14:07,765] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2022-12-28 18:14:07,771] {standard_task_runner.py:52} INFO - Started process 16831 to run task
[2022-12-28 18:14:07,777] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpshadgvoe', '--error-file', '/tmp/tmpayir48ye']
[2022-12-28 18:14:07,778] {standard_task_runner.py:80} INFO - Job 15: Subtask cria_pasta
[2022-12-28 18:14:07,858] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:14:07,967] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/alxavier/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2022-12-28 18:14:07,991] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20221228T211407, end_date=20221228T211407
[2022-12-28 18:14:08,099] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task cria_pasta (unexpected end of template, expected ','.; 16831)
[2022-12-28 18:14:08,115] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-28 18:14:08,264] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:28:37,381] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:28:37,398] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:28:37,399] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:28:37,399] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:28:37,399] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:28:37,445] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2022-12-28 18:28:37,457] {standard_task_runner.py:52} INFO - Started process 18438 to run task
[2022-12-28 18:28:37,469] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmprfvln429', '--error-file', '/tmp/tmpnibclmbp']
[2022-12-28 18:28:37,470] {standard_task_runner.py:80} INFO - Job 19: Subtask cria_pasta
[2022-12-28 18:28:37,621] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:28:37,772] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2022-12-28 18:28:37,783] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:28:37,787] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-26"']
[2022-12-28 18:28:37,812] {subprocess.py:85} INFO - Output:
[2022-12-28 18:28:37,820] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:28:37,882] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20221228T212837, end_date=20221228T212837
[2022-12-28 18:28:37,994] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:28:38,090] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:38:07,272] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:38:07,321] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:38:07,321] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:38:07,324] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:38:07,326] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:38:07,382] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2022-12-28 18:38:07,395] {standard_task_runner.py:52} INFO - Started process 19460 to run task
[2022-12-28 18:38:07,411] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp85w36q3t', '--error-file', '/tmp/tmpajpbg5_b']
[2022-12-28 18:38:07,414] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2022-12-28 18:38:07,655] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:38:07,864] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2022-12-28 18:38:07,866] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:38:07,867] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-26"']
[2022-12-28 18:38:07,894] {subprocess.py:85} INFO - Output:
[2022-12-28 18:38:07,901] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:38:07,997] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20221228T213807, end_date=20221228T213807
[2022-12-28 18:38:08,088] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:38:08,203] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:42:25,250] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:42:25,261] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:42:25,261] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:42:25,261] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:42:25,261] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:42:25,297] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2022-12-28 18:42:25,303] {standard_task_runner.py:52} INFO - Started process 19909 to run task
[2022-12-28 18:42:25,315] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpvts8v36g', '--error-file', '/tmp/tmpkm5ivmmh']
[2022-12-28 18:42:25,316] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2022-12-28 18:42:25,456] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:42:25,641] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2022-12-28 18:42:25,644] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:42:25,645] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-26"']
[2022-12-28 18:42:25,668] {subprocess.py:85} INFO - Output:
[2022-12-28 18:42:25,669] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:42:25,758] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20221228T214225, end_date=20221228T214225
[2022-12-28 18:42:25,832] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:42:25,916] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:44:41,595] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:44:41,623] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:44:41,625] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:44:41,626] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:44:41,627] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:44:41,692] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2022-12-28 18:44:41,699] {standard_task_runner.py:52} INFO - Started process 20186 to run task
[2022-12-28 18:44:41,727] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpe90ysyxy', '--error-file', '/tmp/tmpzd_ommwn']
[2022-12-28 18:44:41,735] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2022-12-28 18:44:41,911] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:44:42,054] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2022-12-28 18:44:42,056] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:44:42,057] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-26"']
[2022-12-28 18:44:42,094] {subprocess.py:85} INFO - Output:
[2022-12-28 18:44:42,097] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:44:42,162] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20221228T214441, end_date=20221228T214442
[2022-12-28 18:44:42,244] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:44:42,341] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-28 18:52:12,439] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:52:12,469] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-12-28 18:52:12,470] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:52:12,481] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-28 18:52:12,481] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-28 18:52:12,538] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2022-12-28 18:52:12,550] {standard_task_runner.py:52} INFO - Started process 21001 to run task
[2022-12-28 18:52:12,561] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpb2aofgkn', '--error-file', '/tmp/tmpcixrji_a']
[2022-12-28 18:52:12,563] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2022-12-28 18:52:12,758] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host alxavier-airflow
[2022-12-28 18:52:12,940] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2022-12-28 18:52:12,945] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-28 18:52:12,946] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/alxavier/Documents/airflowalura/semana=2022-09-26"']
[2022-12-28 18:52:12,974] {subprocess.py:85} INFO - Output:
[2022-12-28 18:52:12,987] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-28 18:52:13,063] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20221228T215212, end_date=20221228T215213
[2022-12-28 18:52:13,164] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-28 18:52:13,310] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
